name: Release Dev Container Templates & Generate Documentation
on:
  workflow_dispatch:

  # Triggered every time when make changes to src/*/devcontainer-template.json file
  # It will skip the template if it is already published for the same version, so it is safe
  push:
    branches: [main]
    paths:
      - src/*/devcontainer-template.json

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main') || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Resolve symlinks
        run: ./scripts/resolve-symlinks.sh

      - name: Publish templates
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish-templates: true
          base-path-to-templates: ./src
          generate-docs: true

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Create PR for generated docs
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          title: Automated documentation update
          branch: automated-documentation-update/${{ github.run_id }}
          delete-branch: true
